# Here you have to specify a list of whitelisted ips.
# Note that you do not need to specify bungee IPs here.
# Those are automatically imported from your bukkit.yml.
# Set them there if you didn't already.
whitelist: []


# Here you have to specify the message sent to the player when kicked.
playerKickMessage: '&cYou have to join through the proxy.'

# Put this to true to print the real IP of every player attempting to connect.
debug: false

# Setup mode, enabled on first run, will automatically whitelist the IP of the
# first player that is detected to connect through bungeecord, kicking the
# other players after 1 second.
# WARNING : This should be set to false once you have whitelisted your bungeecord !
setup: true
