# Here you have to specify a list of whitelisted ips.
# Note that you do not need to specify bungee IPs here. 
# Those are automatically imported from your bukkit.yml.
# Set them there if you didn't already.
whitelist: 
- 127.0.0.1

# Here you have to specify the message sent to the player when kicked.
playerKickMessage: '&cYou have to join through the proxy.'